# ===============================================================
#  Copyright (c) 2025 FR RASTA
# 
#  File ini adalah bagian dari proyek [NAVY USERBOT].
#  Dilarang menyalin, memodifikasi, atau mendistribusikan kode ini
#  tanpa izin tertulis dari pemilik.
# 
#  Untuk informasi lisensi dan hak cipta, silakan lihat file LICENSE.
# ===============================================================





RANDOM_REPLY = [
    "Halo~ ayo ngobrol!",
    "Yo~ sedang stand by.",
    "Ada yang ingin kamu ceritakan?",
    "Selamat datang! Apa kabar?",
    "Aku siap mendengarkanmu.",
    "Cerita dong, aku di sini buat kamu.",
    "Kalau kamu butuh teman ngobrol, aku ada.",
    "Apa yang membuatmu senang hari ini?",
    "Jangan sungkan, aku di sini.",
    "Mau sharing soal apapun, yuk!",
    "Hari kamu gimana?",
    "Lagi capek? Cerita aja ya.",
    "Aku senang bisa menemanimu.",
    "Ngomong sana sini itu asik ya?",
    "Apa rencanamu hari ini?",
    "Suka duka apa yang kamu alami?",
    "Bercerita itu menyenangkan.",
    "Kalau bingung, ngobrol bisa jadi solusi.",
    "Aku senang kalau kamu nyaman ngobrol denganku.",
    "Hai, ada hal seru apa hari ini?",
    "Aku di sini buat membantu.",
    "Berbagi cerita adalah cara yang baik.",
    "Mari kita mulai obrolan yang seru!",
    "Ada cerita lucu gak?",
    "Kamu suka topik apa?",
    "Kalau bosan, ngobrol saja ya!",
    "Aku penasaran soal hobimu.",
    "Cerita yang ingin kamu bagi apa?",
    "Bagaimana perasaanmu hari ini?",
    "Kadang ngobrol itu bikin lega loh.",
    "Mau ngomong apa saja, aku dengerin kok.",
    "Aku di sini untuk menemanimu kapan saja.",
    "Cerita apa yang belum sempat kamu ceritakan?",
    "Soal film, musik, atau apa nih?",
    "Aku suka cerita-cerita inspiratif.",
    "Luangkan waktumu, aku di sini.",
    "Bercerita membantu menyelesaikan masalah.",
    "Ngobrol santai boleh, serius juga gak masalah.",
    "Kamu suka ngobrol soal mimpi?",
    "Ayo mulai petualangan obrolan!",
    "Cerita tentang hal-hal unik dong.",
    "Aku penasaran jawabanmu.",
    "Apa hal terbaik yang terjadi hari ini?",
    "Kamu lagi pengen ngobrol apa sih?",
    "Ada yang pengen kamu tanyain?",
    "Kalau capek, cerita aja ya biar lega.",
    "Aku gak akan bosan dengerinmu",
    "Obrolan seru bikin waktu cepat berlalu.",
    "Suka cerita soal alam atau teknologi?",
    "Hai! Ayo mulai ngobrol asik.",
    "Kalau kamu sedih, aku siap dengarkan.",
    "Apa makanan favoritmu?",
    "Mau aku jadi pendengar setia?",
    "Ada berita menarik gak hari ini?",
    "Mari kita buat harimu lebih cerah.",
    "Aku tertarik dengan duniamu.",
    "Kamu mau ngobrol soal travel?",
    "Jangan ragu bercerita ya.",
    "Aku ingin tahu lebih banyak tentangmu.",
    "Lagi pengen senyum? Aku juga!",
    "Ngobrol seru bikin hati senang.",
    "Ada cerita romantis yang mau dibagi?",
    "Apa musik favoritmu akhir-akhir ini?",
    "Aku ingin jadi teman ngobrol terbaikmu.",
    "Hari ini ada hal lucu gak?",
    "Aku di sini kalau kamu butuh saran.",
    "Gimana kalau kita bahas hobi?",
    "Cerita misteri seru gak yang kamu tahu?",
    "Siap menjadi teman dalam suka dan duka.",
    "Ayo kita buat obrolan jadi santai dan asik.",
    "Kalau kamu senang, aku juga senang.",
    "Mau tahu sesuatu yang baru?",
    "Berbagi cerita itu penting loh.",
    "Aku suka dengar cerita bebas.",
    "Kamu penggemar film atau buku?",
    "Ayo sambung obrolannya!",
    "Kalau kamu penasaran tentang sesuatu, tanya aku aja.",
    "Mari kita buat obrolan ini penuh warna.",
    "Kamu suka hewan peliharaan?",
    "Punya pengalaman unik yang mau dibagi gak?",
    "Aku penasaran dengan cita-citamu.",
    "Lagi pengen nostalgia? Cerita aja.",
    "Apa impian terbesarmu?",
    "Ayo kita ngobrol santai sampai lupa waktu.",
    "Kamu suka cuaca yang gimana?",
    "Ada tempat keren yang kamu kunjungi terakhir?",
    "Aku di sini buat menjadi tempatmu curhat.",
    "Mau dengar cerita motivasi?",
    "Apa buku terakhir yang kamu baca?",
    "Bercerita itu bisa bikin hati lega.",
    "Kamu suka olahraga apa?",
    "Ayo ceritakan pengalaman serumu!",
    "Aku selalu senang mendengar kabar darimu.",
    "Ngomongin masa kecil seru gak?",
    "Aku bisa jadi teman ngobrol kapan saja.",
    "Kalau kamu sedih, aku selalu di sini.",
    "Ayo mulai hari dengan obrolan positif!",
    "Aku penasaran makanan favoritmu nih.",
    "Kamu tipe orang yang suka tantangan?",
    "Ayolah, jangan segan untuk cerita.",
    "Mau tahu tanya jawab asik?",
    "Aku suka ngobrol soal mimpi dan harapan.",
    "Punya rencana liburan gak?",
    "Ayo berbagi hal-hal menyenangkan.",
    "Aku di sini untuk mendukungmu.",
    "Siapa tokoh favoritmu?",
    "Kalau kamu mau cerita, aku siap dengarkan.",
    "Obrolan ringan itu penyemangat hari.",
    "Apakah kamu suka musik?",
    "Maukah kamu berbagi rahasia senyummu?",
    "Ceritakan apa saja, aku ingin tahu.",
    "Aku senang bisa jadi teman baikmu.",
    "Kamu merasa bagaimana hari ini?",
    "Aku di sini untuk menemanimu sepanjang waktu.",
    "Kamu suka warna apa?",
    "Mari kita ngobrol soal hal-hal yang kamu sukai.",
    "Aku selalu ada jika kamu butuh teman.",
    "Ayo kita bikin hari ini menyenangkan.",
    "Kamu suka main game apa?",
    "Aku tertarik dengan pendapatmu.",
    "Aku senang kalau kamu bahagia.",
    "Punya cerita unik gak hari ini?",
    "Obrolan kita bisa sampai subuh loh!",
    "Kalau kamu butuh hiburan, aku siap.",
    "Kamu suka seni atau musik?",
    "Aku ingin jadi bagian dari harimu.",
    "Apa yang membuatmu semangat?",
    "Cerita lucu apa yang kamu tahu?",
    "Aku senang bersama kamu ngobrol.",
    "Mau kita bahas film favorit?",
    "Kamu punya tujuan hidup yang keren ya.",
    "Punya pengalaman seru di luar rumah?",
    "Aku di sini untuk ngedukung kamu.",
    "Hari ini ada kejadian apa?",
    "Kalau kamu butuh ide, aku punya banyak lho.",
    "Kamu suka berpetualang?",
    "Mau cerita soal teman-temanmu?",
    "Aku ingin tahu apa yang kamu pikirkan.",
    "Kalau kamu bosan, ngomong aja sama aku.",
    "Aku siap jadi pendengar yang baik.",
    "Kamu suka musim apa?",
    "Mari kita buat cerita baru bersama.",
    "Lagi pengen denger lagu apa?",
    "Aku akan jadi teman ngobrol setiamu.",
    "Kadang ngobrol itu bikin hati hangat lho.",
    "Punya mimpi aneh pernah gak?",
    "Aku suka dengar cerita perjalananmu.",
    "Kamu penyuka kopi atau teh?",
    "Ayo kita pelajari hal-hal baru bareng.",
    "Aku senang kalau kamu percaya sama aku.",
    "Apa warna kesukaanmu?",
    "Cerita apa yang bisa bikin kamu senyum?",
    "Aku ingin ngobrol tanpa batas denganmu.",
    "Kamu suka baca novel atau komik?",
    "Obrolan kita itu keren banget ya.",
    "Mau aku jadi teman pribadi kamu?",
    "Kamu suka binatang apa?",
    "Aku sini menemanimu kapan saja.",
    "Ayo kita buat hari ini berkesan.",
    "Kamu ada rencana seru minggu ini?",
    "Aku penasaran makanan favoritmu.",
    "Kamu suka jalan-jalan kemana?",
    "Aku bisa jadi tempat rahasiamu.",
    "Apa hal paling menyenangkan hari ini?",
    "Ngobrol sama aku itu asik banget!",
    "Aku senang kamu ngajak ngobrol.",
    "Mau aku ceritakan hal lucu?",
    "Kamu suka film komedi atau drama?",
    "Aku ingin jadi bagian cerita hidupmu.",
    "Apa lagu favoritmu saat ini?",
    "Ayo kita buat momen tak terlupakan.",
    "Kamu suka makanan manis atau asin?",
    "Aku penasaran dengan ide-idemu.",
    "Cerita yang buat kamu ketawa dong!",
    "Aku di sini kalau kamu butuh teman curhat.",
    "Kamu suka olahraga apa?",
    "Hari ini ada hal yang bikin kamu bahagia?",
    "Aku ingin mendengar cerita masa kecilmu.",
    "Kamu suka pelajaran apa waktu sekolah?",
    "Mari kita bicarakan topik favoritmu!",
    "Aku siap jadi pendukung setiamu.",
    "Punya hewan peliharaan yang unik?",
    "Aku di sini buat kamu, kapan saja kamu butuh.",
    "Kalau kamu capek, cerita aja ya.",
    "Aku suka cerita yang membuat hati hangat.",
    "Apa yang kamu ingin capai bulan ini?",
    "Aku penasaran tentang duniamu.",
    "Kamu suka jenis musik apa?",
    "Ngomong apa saja, aku selalu di sini.",
    "Aku ingin tahu apa yang bikin kamu senang.",
    "Ada cerita misterius yang pernah kamu dengar?",
    "Aku suka ngobrol santai seperti ini.",
    "Kamu suka pergi ke alam bebas?",
    "Mari kita buat sesi ngobrol yang asik.",
    "Apa hal yang membuat kamu bangga?",
    "Mau cerita soal liburan terakhirmu?",
    "Aku senang setiap kali ngobrol denganmu.",
    "Apa makanan favorit keluargamu?",
    "Kalau kamu sedih, aku akan ada di sini.",
    "Aku penasaran tentang gaya hidupmu.",
    "Kamu suka baca berita apa?",
    "Mari kita coba hal baru hari ini!",
    "Aku siap jadi teman ngobrol setiamu.",
    "Kamu suka film aksi atau romantis?",
    "Cerita apa yang paling berkesan buatmu?",
    "Aku ingin denger cerita tentang temanmu.",
    "Mau kita ngobrol sampai malam?",
    "Kamu suka kopi atau teh saat santai?",
    "Aku di sini kalau kamu bingung mau cerita apa.",
    "Ayo kita bikin cerita yang seru bareng.",
    "Aku tertarik sama hobimu.",
    "Apa kegiatan favoritmu di akhir pekan?",
    "Aku senang jadi bagian dari obrolanmu.",
    "Kamu suka musim panas atau musim hujan?",
    "Mari kita buat obrolan ini penuh energi.",
    "Aku dapat kabar baik nih, mau dengar?",
    "Kamu suka main alat musik?",
    "Aku di sini untuk nemenin kamu kapan pun.",
    "Ayo cerita soal cita-citamu!",
    "Aku penasaran sama bakat tersembunyimu.",
    "Kalau kamu capek, rehat sebentar ya.",
    "Aku suka kalau kita bisa saling berbagi cerita.",
    "Kamu suka nonton drama Korea?",
    "Mari kita ngobrol soal tempat-tempat favoritmu.",
    "Aku ingin tahu apa yang membuatmu termotivasi.",
    "Mau aku jadi pendengar rahasiamu?",
    "Kamu punya kebiasaan unik gak?",
    "Aku selalu di sini kalau kamu butuh teman.",
    "Apa makanan khas daerahmu yang kamu suka?",
    "Aku di sini supaya kamu gak merasa sendiri.",
    "Ngobrol denganmu itu menyenangkan.",
    "Aku ingin tahu lebih banyak tentang keluargamu.",
    "Ayo kita mulai obrolan baru yang seru!",
    "Kamu suka menulis atau menggambar?",
    "Mau cerita soal pengalaman berharga?",
    "Aku senang bisa mendukung kamu setiap saat.",
    "Apa pencapaian terbesar yang kamu banggakan?",
    "Aku penasaran topik apa yang paling kamu suka.",
    "Kamu suka cerita horor gak?",
    "Mari kita buat hari ini penuh inspirasi.",
    "Aku di sini buat jadi teman terbaikmu.",
    "Kamu pernah punya pengalaman lucu yang nyesek?",
    "Aku siap mendengarkan apapun yang kamu ceritakan.",
    "Apa yang membuat kamu tertawa hari ini?",
    "Aku suka ngobrol bareng kamu.",
    "Mau aku kasih tebakan lucu?",
    "Kamu suka lagu apa paling sering didengar?",
    "Aku ingin kita tetap teman baik selamanya.",
    "Cerita apa yang bikin kamu bahagia?",
    "Aku penasaran sama rencana masa depanmu.",
    "Kamu suka hewan apa di kebun binatang?",
    "Ayo kita buat momen obrolan yang berkesan.",
    "Aku di sini buat nemenin kamu setiap waktu.",
    "Kalau kamu lagi sedih, ceritakan padaku ya.",
    "Aku senang kamu punya cerita buat dibagi.",
    "Apa hal yang paling kamu hargai dalam hidup?",
    "Aku tertarik sama hobi unikmu.",
    "Kamu suka makanan pedas atau manis?",
    "Aku mau jadi teman ngobrol yang asik buat kamu.",
    "Mau cerita soal kenangan masa kecilmu?",
    "Aku di sini buat kamu, selalu.",
    "Ayo kita bercerita sampai lupa waktu.",
    "Aku penasaran sama tempat impianmu buat liburan.",
    "Kamu suka film animasi gak?",
    "Ngomong apa aja, aku bakal dengerin dengan baik.",
    "Aku suka kalau obrolan kita asik kayak gini.",
    "Kalau kamu stres, aku bisa bantu kamu rileks.",
    "Aku bantu kamu buat ngilangin suntuk ya.",
    "Kamu paling suka ngapain waktu weekend?",
    "Ayo kita bagi cerita seru bareng-bareng.",
    "Aku senang kalau kamu nyaman ngobrol denganku.",
    "Mau cerita soal pengalaman unik kamu?",
    "Aku di sini untuk jadi teman ngobrol kamu yang setia.",
    "Apa lagu favoritmu sepanjang masa?",
    "Aku penasaran sama buku favoritmu.",
    "Kamu suka cuaca cerah atau hujan-hujan santai?",
    "Ayo kita buat hari ini penuh tawa.",
    "Aku ingin mengambil bagian dalam ceritamu.",
    "Mau aku ceritain lelucon?",
    "Kamu suka teh manis atau kopi hitam?",
    "Aku siap jadi teman yang selalu mendukungmu.",
]



jodoh_data = [
    {
        "ras": "Vietnam",
        "warnakulit": "sawo cerah",
        "warnarambut": "hitam",
        "penjelasan": "Pasanganmu akan mendukungmu tanpa syarat dalam keadaan apapun."
    },
    {
        "ras": "Bugis",
        "warnakulit": "kuning langsat",
        "warnarambut": "keriting halus",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Korea",
        "warnakulit": "putih bersih",
        "warnarambut": "keriting halus",
        "penjelasan": "Pasanganmu akan mendukungmu tanpa syarat dalam keadaan apapun."
    },
    {
        "ras": "Manado",
        "warnakulit": "putih bersih",
        "warnarambut": "keriting halus",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Korea",
        "warnakulit": "gelap eksotis",
        "warnarambut": "coklat",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    },
    {
        "ras": "Sunda",
        "warnakulit": "sawo cerah",
        "warnarambut": "hitam",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Eropa",
        "warnakulit": "putih cerah",
        "warnarambut": "merah",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Manado",
        "warnakulit": "putih bersih",
        "warnarambut": "abu-abu",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Papua",
        "warnakulit": "kuning langsat",
        "warnarambut": "hitam lurus",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Madura",
        "warnakulit": "putih cerah",
        "warnarambut": "coklat",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Batak",
        "warnakulit": "kuning langsat",
        "warnarambut": "keriting halus",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Manado",
        "warnakulit": "coklat muda",
        "warnarambut": "coklat",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Korea",
        "warnakulit": "sawo matang",
        "warnarambut": "coklat",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "India",
        "warnakulit": "sawo cerah",
        "warnarambut": "abu-abu",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Thailand",
        "warnakulit": "sawo matang",
        "warnarambut": "coklat",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Bali",
        "warnakulit": "coklat muda",
        "warnarambut": "pirang",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Jawa",
        "warnakulit": "gelap eksotis",
        "warnarambut": "hitam lurus",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Korea",
        "warnakulit": "sawo cerah",
        "warnarambut": "coklat",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Tionghoa",
        "warnakulit": "putih bersih",
        "warnarambut": "hitam lurus",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Bali",
        "warnakulit": "sawo cerah",
        "warnarambut": "hitam lurus",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Minang",
        "warnakulit": "gelap eksotis",
        "warnarambut": "hitam lurus",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Bugis",
        "warnakulit": "sawo matang",
        "warnarambut": "coklat",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Sunda",
        "warnakulit": "gelap eksotis",
        "warnarambut": "pirang",
        "penjelasan": "Dia membawa ketenangan, seakan dunia tidak lagi menakutkan."
    },
    {
        "ras": "Papua",
        "warnakulit": "coklat muda",
        "warnarambut": "coklat",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Manado",
        "warnakulit": "sawo cerah",
        "warnarambut": "pirang",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Jawa",
        "warnakulit": "kuning langsat",
        "warnarambut": "keriting halus",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Korea",
        "warnakulit": "sawo matang",
        "warnarambut": "abu-abu",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Minang",
        "warnakulit": "kuning langsat",
        "warnarambut": "pirang",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Tionghoa",
        "warnakulit": "kuning langsat",
        "warnarambut": "merah",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    },
    {
        "ras": "Jepang",
        "warnakulit": "kuning langsat",
        "warnarambut": "abu-abu",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "India",
        "warnakulit": "gelap eksotis",
        "warnarambut": "coklat",
        "penjelasan": "Pasanganmu akan mendukungmu tanpa syarat dalam keadaan apapun."
    },
    {
        "ras": "Tionghoa",
        "warnakulit": "sawo cerah",
        "warnarambut": "merah",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Papua",
        "warnakulit": "coklat muda",
        "warnarambut": "hitam lurus",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Vietnam",
        "warnakulit": "putih cerah",
        "warnarambut": "merah",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Bugis",
        "warnakulit": "kuning langsat",
        "warnarambut": "hitam lurus",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Korea",
        "warnakulit": "gelap eksotis",
        "warnarambut": "merah",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Eropa",
        "warnakulit": "coklat muda",
        "warnarambut": "coklat",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Papua",
        "warnakulit": "coklat muda",
        "warnarambut": "merah",
        "penjelasan": "Dia membawa ketenangan, seakan dunia tidak lagi menakutkan."
    },
    {
        "ras": "Manado",
        "warnakulit": "sawo cerah",
        "warnarambut": "coklat",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Bali",
        "warnakulit": "sawo matang",
        "warnarambut": "abu-abu",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    },
    {
        "ras": "Manado",
        "warnakulit": "sawo matang",
        "warnarambut": "hitam lurus",
        "penjelasan": "Dia membawa ketenangan, seakan dunia tidak lagi menakutkan."
    },
    {
        "ras": "Tionghoa",
        "warnakulit": "sawo matang",
        "warnarambut": "coklat",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Korea",
        "warnakulit": "putih cerah",
        "warnarambut": "abu-abu",
        "penjelasan": "Dia membawa ketenangan, seakan dunia tidak lagi menakutkan."
    },
    {
        "ras": "Batak",
        "warnakulit": "putih cerah",
        "warnarambut": "keriting halus",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Bugis",
        "warnakulit": "gelap eksotis",
        "warnarambut": "coklat",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Manado",
        "warnakulit": "sawo cerah",
        "warnarambut": "pirang",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Arab",
        "warnakulit": "sawo matang",
        "warnarambut": "pirang",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Vietnam",
        "warnakulit": "kuning langsat",
        "warnarambut": "hitam",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Vietnam",
        "warnakulit": "sawo matang",
        "warnarambut": "abu-abu",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Papua",
        "warnakulit": "kuning langsat",
        "warnarambut": "merah",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Thailand",
        "warnakulit": "gelap eksotis",
        "warnarambut": "merah",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Sunda",
        "warnakulit": "kuning langsat",
        "warnarambut": "keriting halus",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Madura",
        "warnakulit": "sawo cerah",
        "warnarambut": "abu-abu",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Bugis",
        "warnakulit": "sawo matang",
        "warnarambut": "coklat",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Manado",
        "warnakulit": "putih cerah",
        "warnarambut": "merah",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Minang",
        "warnakulit": "coklat muda",
        "warnarambut": "hitam",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    },
    {
        "ras": "Eropa",
        "warnakulit": "putih bersih",
        "warnarambut": "merah",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Arab",
        "warnakulit": "putih cerah",
        "warnarambut": "hitam",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Batak",
        "warnakulit": "sawo cerah",
        "warnarambut": "abu-abu",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Sunda",
        "warnakulit": "kuning langsat",
        "warnarambut": "abu-abu",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Madura",
        "warnakulit": "putih bersih",
        "warnarambut": "coklat",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Vietnam",
        "warnakulit": "kuning langsat",
        "warnarambut": "pirang",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Korea",
        "warnakulit": "putih bersih",
        "warnarambut": "hitam lurus",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Jepang",
        "warnakulit": "putih cerah",
        "warnarambut": "hitam",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Aceh",
        "warnakulit": "sawo cerah",
        "warnarambut": "hitam lurus",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Jawa",
        "warnakulit": "putih bersih",
        "warnarambut": "merah",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Aceh",
        "warnakulit": "gelap eksotis",
        "warnarambut": "coklat",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Tionghoa",
        "warnakulit": "sawo cerah",
        "warnarambut": "hitam lurus",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Ambon",
        "warnakulit": "gelap eksotis",
        "warnarambut": "hitam lurus",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Jawa",
        "warnakulit": "putih cerah",
        "warnarambut": "pirang",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Eropa",
        "warnakulit": "gelap eksotis",
        "warnarambut": "keriting halus",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Batak",
        "warnakulit": "sawo matang",
        "warnarambut": "abu-abu",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Bali",
        "warnakulit": "coklat muda",
        "warnarambut": "abu-abu",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Eropa",
        "warnakulit": "sawo matang",
        "warnarambut": "merah",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Papua",
        "warnakulit": "sawo matang",
        "warnarambut": "hitam",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Sunda",
        "warnakulit": "coklat muda",
        "warnarambut": "hitam lurus",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Tionghoa",
        "warnakulit": "putih cerah",
        "warnarambut": "abu-abu",
        "penjelasan": "Pasanganmu akan mendukungmu tanpa syarat dalam keadaan apapun."
    },
    {
        "ras": "Batak",
        "warnakulit": "sawo cerah",
        "warnarambut": "keriting halus",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    },
    {
        "ras": "Korea",
        "warnakulit": "putih cerah",
        "warnarambut": "abu-abu",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    },
    {
        "ras": "Vietnam",
        "warnakulit": "putih bersih",
        "warnarambut": "keriting halus",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Jepang",
        "warnakulit": "sawo cerah",
        "warnarambut": "pirang",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Vietnam",
        "warnakulit": "coklat muda",
        "warnarambut": "merah",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Jawa",
        "warnakulit": "putih cerah",
        "warnarambut": "abu-abu",
        "penjelasan": "Pasanganmu akan mendukungmu tanpa syarat dalam keadaan apapun."
    },
    {
        "ras": "Korea",
        "warnakulit": "gelap eksotis",
        "warnarambut": "pirang",
        "penjelasan": "Jodohmu adalah pendengar yang baik dan selalu memberi solusi saat kamu bingung."
    },
    {
        "ras": "Aceh",
        "warnakulit": "gelap eksotis",
        "warnarambut": "keriting halus",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Sunda",
        "warnakulit": "kuning langsat",
        "warnarambut": "pirang",
        "penjelasan": "Dia akan membuatmu merasa berharga dan dicintai setiap saat."
    },
    {
        "ras": "Dayak",
        "warnakulit": "kuning langsat",
        "warnarambut": "hitam lurus",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Jawa",
        "warnakulit": "kuning langsat",
        "warnarambut": "coklat",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Madura",
        "warnakulit": "sawo matang",
        "warnarambut": "merah",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Minang",
        "warnakulit": "putih bersih",
        "warnarambut": "keriting halus",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Sunda",
        "warnakulit": "sawo matang",
        "warnarambut": "hitam",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Dayak",
        "warnakulit": "gelap eksotis",
        "warnarambut": "hitam",
        "penjelasan": "Pasanganmu akan mendukungmu tanpa syarat dalam keadaan apapun."
    },
    {
        "ras": "Ambon",
        "warnakulit": "putih cerah",
        "warnarambut": "hitam lurus",
        "penjelasan": "Pasanganmu penuh semangat dan tidak pernah menyerah dalam mengejar impian."
    },
    {
        "ras": "Dayak",
        "warnakulit": "gelap eksotis",
        "warnarambut": "pirang",
        "penjelasan": "Sosoknya unik, berbeda dari yang lain, dan justru itulah daya tariknya."
    },
    {
        "ras": "Korea",
        "warnakulit": "coklat muda",
        "warnarambut": "hitam lurus",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    },
    {
        "ras": "Batak",
        "warnakulit": "coklat muda",
        "warnarambut": "merah",
        "penjelasan": "Jodohmu adalah sosok yang setia dan akan menemanimu hingga akhir hayat."
    },
    {
        "ras": "Bugis",
        "warnakulit": "putih bersih",
        "warnarambut": "pirang",
        "penjelasan": "Dia sosok yang sabar, penyayang, dan tidak pernah marah tanpa alasan."
    },
    {
        "ras": "Thailand",
        "warnakulit": "putih bersih",
        "warnarambut": "pirang",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    },
    {
        "ras": "Vietnam",
        "warnakulit": "gelap eksotis",
        "warnarambut": "keriting halus",
        "penjelasan": "Kamu akan mendapatkan pasangan yang cerdas dan mampu membuat keputusan bijak."
    },
    {
        "ras": "Eropa",
        "warnakulit": "kuning langsat",
        "warnarambut": "keriting halus",
        "penjelasan": "Senyumnya mampu meruntuhkan segala gundah yang kamu simpan selama ini."
    }
]



FITNAH_MESSAGES = [
    "Orang kayak @user cuma pantes dijadiin contoh buruk di seminar motivasi.",
    "Semua masalah hidup lo tuh datang dari sifat lo sendiri, @user.",
    "Kadang gue mikir, @user itu produk gagal manusia.",
    "Percaya deh, dunia bakal jauh lebih tenang kalau @user nggak ada.",
    "Nggak heran @user dijauhin semua orang, kelakuan lo lebih busuk dari tong sampah.",
    "Sumpah ya, @user itu definisi orang yang bikin pusing tanpa usaha.",
    "Liat @user tuh kayak liat kegagalan berjalan.",
    "Kayaknya Tuhan lagi nguji kesabaran orang sekitar lo, @user.",
    "Jangan sok baik @user, jejak digital lo lebih jahat dari karma.",
    "Kalau goblok ada level, @user tuh udah prestasi nasional.",
    "Orang kayak @user bikin gue sadar kenapa manusia ada kasta.",
    "Dari semua hal menjijikkan di dunia ini, @user tetap masuk top 3.",
    "@user bisa bikin suasana rusak cuma dengan buka mulut.",
    "Kehadiran @user itu kayak lag bug di game, bikin rusak semuanya.",
    "Setiap kali @user ngomong, IQ ruangan turun 30 poin.",
    "Kalau ada lomba orang paling nggak berguna, @user pasti juara umum.",
    "Semua aib ada di lo, @user. Tapi lo malah bangga.",
    "Maaf ya @user, bukan gue benci lo, emang lo layak dibenci.",
    "Dosa-dosa lo, @user, bisa jadi season baru drama neraka.",
    "Gue yakin Tuhan ngeluh tiap ngeliat @user minta rezeki.",
    "Lo tuh toxic, @user. Bukan karena orang salah paham, tapi emang lo bangsat.",
    "@user itu kayak virus, sekali deket, semua jadi hancur.",
    "Karma pasti punya list prioritas, dan nama lo, @user, paling atas.",
    "Orang kayak @user tuh gak butuh musuh, karena diri lo sendiri udah penghancur.",
    "Muka bisa disenyumin, @user, tapi kelakuan lo menjijikkan.",
    "Gue salut, @user bisa hidup dengan mental sekotor itu.",
    "Semua hal negatif ada di @user, tinggal dikasih label aja.",
    "@user, bahkan bayangan lo malu ngikutin lo.",
    "Satu-satunya hal positif dari @user tuh cuma hasil swab.",
    "@user itu manusia yang berhasil memalukan spesiesnya sendiri.",
    "Kalau hidup lo itu buku, genre-nya pasti 'tragikomedi jijik'.",
    "Orang kayak @user tuh kayak malware: gak kelihatan tapi bikin rusak.",
    "Lo itu bahan gosip favorit iblis, @user.",
    "Gue gak tahu siapa yang salahin lo lahir, tapi mereka mungkin gak salah.",
    "Tiap lo muncul, harapan umat manusia mundur 10 tahun, @user.",
    "@user, bahkan suara kentut lebih bisa diterima daripada pendapat lo.",
    "Orang kayak lo tuh cocoknya disimpen di recycle bin.",
    "Dunia akan sedikit lebih waras tanpa kehadiran lo, @user.",
    "Mungkin hidup lo drama, tapi lo bukan tokoh utama, @user. Lo cuma masalahnya.",
    "@user selalu bikin capek tanpa harus ngapa-ngapain.",
    "Lo tuh bukan dibenci karena jujur, tapi karena lo emang sampah.",
    "Semua karma baik gue luntur cuma karena harus liat muka @user.",
    "Mikir sebelum ngomong tuh penting, coba lo belajar, @user.",
    "Keliatan sih @user dilahirkan bukan buat jadi solusi.",
    "@user itu kayak popup iklan di web bajakan: ngeselin, norak, dan pengen ditutup.",
    "Jadi lo bangga gitu disukai cuma karena pura-pura? Dasar palsu, @user.",
    "Lo itu problem, bukan korban. Jangan sok playing victim, @user.",
    "@user selalu hadir di saat yang salah, ngomong yang salah, dengan cara yang paling salah.",
    "Lo pikir semua orang suka lo? Nggak bro, bahkan cermin lo jijik ngeliat lo, @user.",
    "Mau jadi baik kayak gimana pun, @user, dasar lo udah busuk.",
    "@user itu bukan toxic lagi, lo racun full package.",
    "Gue doain semoga lo sadar betapa gak pentingnya lo selama ini.",
    "Kadang gue mikir, semesta kasih lo kesempatan buat berubah, tapi lo malah makin bejat, @user.",
    "Lo bangga bikin orang capek mental? Keren, lo sukses jadi beban, @user.",
    "Kalau nyusahin orang jadi profesi, @user udah jadi CEO.",
    "Lo jalan ke mana pun, aura negatif ikut semua. Bukan mistis, itu lo, @user.",
    "@user bener-bener paket komplit: bodoh, sok tau, dan nggak tahu malu.",
    "Lo gak punya malu, tapi masih bisa ngaku punya prinsip? Ngimpi lo, @user.",
    "Semua rasa sabar orang di sekitarmu tuh terbuang sia-sia ke lo, @user.",
    "Banyak orang salah, tapi lo tuh konsisten, @user: salah terus.",
    "@user mungkin punya hati, tapi kayaknya udah expired.",
    "Setiap keputusan lo tuh kayak konten prank: nggak lucu dan nyusahin orang.",
    "Lo tuh bukan toxic lagi, lo iritasi, @user.",
    "Kalau semua kegagalan dikumpulin, @user bisa jadi perwujudannya.",
    "Jangan bangga kalau orang takut lo, @user. Itu bukan respek, itu jijik.",
    "@user tuh bukan puncak masalah, lo fondasi dari kekacauan hidup banyak orang.",
    "Lo bukan misunderstood, @user. Lo emang nyebelin sejak lahir.",
    "Kalo ada ajang penghancur mood, @user bisa jadi duta utama.",
    "Lo suka bilang 'cuma becanda', padahal emang lo jahat, @user.",
    "Semua kebaikan di dunia ini gak bisa nutupin satu keburukan lo yang parah, @user.",
    "Lo bukan pencari perhatian, @user. Lo pemaksa simpati yang gagal.",
    "Kalo jadi beban ada gaji, @user udah kaya dari dulu.",
    "Jangan sok sedih ya, @user. Orang lain lebih menderita karena lo.",
    "Lo itu versi buruk dari karakter antagonis yang gagal ditulis.",
    "Kalo karma nggak nyamperin lo sekarang, mungkin lagi nabung buat total, @user.",
    "Kadang pengen bantu lo, @user, tapi gak ada yang bisa diselamatkan.",
    "Lo jangan nyari validasi, @user. Bahkan validasi pun malu deket lo.",
    "Setiap lo buka mulut, harapan orang mati satu-satu.",
    "@user tuh kayak air kotor: nggak bisa diminum, tapi bikin basah semua yang bersih.",
    "Semua pengorbanan yang dikasih ke lo, @user, jatuhnya mubazir.",
    "@user kayak sinyal di tempat sepi: nggak guna dan bikin kesel.",
    "Nggak usah pamer pencapaian, @user. Lo berhasil nyusahin aja udah cukup.",
    "Sadar diri tuh bukan kelemahan, @user. Tapi kayaknya lo kebal sama itu.",
    "Lo tuh alarm gangguan, bukan alarm motivasi.",
    "Kalo hidup itu game, @user tuh bug paling parah yang belum di-fix.",
    "Kadang gue doain lo berubah, @user. Tapi lo tetep goblok dan bangga.",
    "ati ati bro @user suka coli",
    "eh, tau nggak? @user sering ngutang nggak bayar",
    "waduh, @user katanya ketahuan ngintip kamar mandi tetangga",
    "bro, hati-hati sama @user, dia suka makan nggak bayar",
    "@user, katanya kamu jago joget TikTok ya?",
    "anjay, @user hobinya tidur di kelas",
    "muka nya @user kek kontol",
    "tau nggak? @user kemarin ketahuan curhat ke kucing.",
    "@user, katanya kemarin dipanggil guru karena tidur di meja",
    "eh, jangan-jangan @user sering nyolong Wifi tetangga?",
    "gila, @user ternyata koleksi meme-nya ribuan",
    "@user pernah makan bakso bayar pakai daun",
    "waduh, katanya @user ketahuan nge-stalk mantan semalaman",
    "@user, kemarin disuruh nyanyi malah nyanyi lagu iklan",
    "anjir, @user hobi banget rebutan colokan di kelas",
    "tau nggak? @user kalau di kantin suka ngambil gorengan dulu baru bayar 3 hari kemudian",
    "gokil, @user ternyata punya akun fake buat stalking gebetan",
    "bro, katanya @user pernah ketahuan nangis gara-gara kalah main game",
    "parah, @user kemarin ngaku-ngaku jadi selebgram padahal followers cuma 10",
    "woy @user, jangan suka mandi cuma pas ulang tahun aja dong",
    "eh, katanya @user suka tidur sambil ngorok keras banget sampai tetangga kebangun",
    "tau nggak? @user ternyata sering bikin status galau tiap malem",
    "waduh, @user kalau ditagih utang suka pura-pura lupa",
    "gila, @user hobinya ngakak sendiri pas baca chat",
    "@user, kemarin ngaku-ngaku punya mobil, pas dicek cuma mainan remote control",
    "bro, hati-hati sama @user, dia suka minjem barang terus lupa balikin",
    "@user suka banget ngedraft chat panjang, tapi nggak pernah dikirim",
    "anjay, @user ternyata suka karaoke lagu anak-anak di kamar mandi",
    "waduh, katanya @user pernah nulis surat cinta terus malu sendiri",
    "tau nggak? @user kemarin ke warung malah lupa bawa duit",
    "@user sering banget upload story makanan padahal itu makanan orang lain",   
]

ROAST_MESSAGES = [
    "Buka chat @user bisa jadi latihan sabar.",
    "Orang sabar diuji kalau ada @user.",
    "@user masuk grup kayak spam link bodong.",
    "Dan @user selalu jadi alasan orang cabut grup.",
    "@user hadir = turunnya standar grup.",
    "@user ngasih vibes... vibes untuk left.",
    "Kalau grup ini berat, itu karena ada @user.",
    "Bikin grup ini chaos? Gampang. Tambah @user.",
    "Auto skip kalau ada @user muncul.",
    "Setiap grup ada badut, dan itu @user.",
    "@user = antivirus gagal deteksi.",
    "@user bikin suasana grup kayak server mati.",
    "@user itu alasan kenapa mute grup itu fitur penting.",
    "@user itu glitch di percakapan.",
    "@user muncul, mendadak semua pengen left.",
    "Jangan biarkan @user merasa relevan.",
    "Satu kata: @user.",
    "@user tiap ngetik, developer Telegram nangis.",
    "Standar humor anjlok tiap @user bercanda.",
    "@user itu bukan toxic, tapi limbah digital.",
    "Dunia maya lebih baik tanpa @user.",
    "Masalah kompleks biasanya berawal dari @user.",
    "Setiap @user buka chat, IQ turun 10 poin.",
    "@user itu bukti nyata bahwa tidak semua orang harus bicara.",
    "Btw, @user itu konten cringe tiap hari.",
    "Kalau kamu merasa nggak guna, ingat @user lebih parah.",
    "@user aktif tapi cuma jadi background noise.",
    "Gini-gini, yang paling ngerepotin ya @user.",
    "@user cocok jadi test case untuk kesabaran manusia.",
    "@user itu kayak bug yang nggak bisa di-fix.",
    "Mau detox digital? Mute @user.",
    "@user muncul, IQ grup menyesuaikan.",
    "Grup ini penuh warna, kecuali @user, dia abu-abu.",
    "Fun fact: @user itu benchmark kegabutan.",
    "@user cocok jadi hiasan grup, nggak berguna tapi kelihatan.",
    "@user kayak sinyal di gunung, nggak berguna.",
    "Bot pun bisa error baca chat-nya @user.",
    "@user itu versi beta dari kegagalan sosial.",
    "@user datang grup cuma buat nambah jumlah, bukan kualitas.",
    "@user muncul, mendadak semua pengen left.",
    "Kalau grup ini berat, itu karena ada @user.",
    "Dan @user selalu jadi alasan orang cabut grup.",
    "Dan @user selalu jadi alasan orang cabut grup.",
    "Buka chat @user bisa jadi latihan sabar.",
    "Btw, @user itu konten cringe tiap hari.",
    "Fun fact: @user itu benchmark kegabutan.",
    "Masalah kompleks biasanya berawal dari @user.",
    "Kalau grup ini berat, itu karena ada @user.",
    "Dan @user selalu jadi alasan orang cabut grup.",
    "@user itu bukan toxic, tapi limbah digital.",
    "Setiap grup ada badut, dan itu @user.",
    "@user masuk grup kayak spam link bodong.",
    "@user tiap ngetik, developer Telegram nangis.",
    "@user itu alasan kenapa mute grup itu fitur penting.",
    "@user cocok jadi test case untuk kesabaran manusia.",
    "@user hadir = turunnya standar grup.",
    "@user aktif tapi cuma jadi background noise.",
    "@user itu bukan toxic, tapi limbah digital.",
    "Bot pun bisa error baca chat-nya @user.",
    "@user itu kayak bug yang nggak bisa di-fix.",
    "Kalau kamu merasa nggak guna, ingat @user lebih parah.",
    "Masalah kompleks biasanya berawal dari @user.",
    "Fun fact: @user itu benchmark kegabutan.",
    "@user masuk grup kayak spam link bodong.",
    "Grup ini penuh warna, kecuali @user, dia abu-abu.",
    "@user itu alasan kenapa mute grup itu fitur penting.",
    "Dan @user selalu jadi alasan orang cabut grup.",
    "Orang sabar diuji kalau ada @user.",
    "Buka chat @user bisa jadi latihan sabar.",
    "@user itu alasan kenapa mute grup itu fitur penting.",
    "Jangan biarkan @user merasa relevan.",
    "Bot pun bisa error baca chat-nya @user.",
    "Setiap @user buka chat, IQ turun 10 poin.",
    "@user itu bukan toxic, tapi limbah digital.",
    "@user nyumbang rame doang, isi nol.",
    "@user cocok jadi hiasan grup, nggak berguna tapi kelihatan.",
    "Btw, @user itu konten cringe tiap hari.",
    "Kalau grup ini berat, itu karena ada @user.",
    "Gini-gini, yang paling ngerepotin ya @user.",
    "@user masuk grup kayak spam link bodong.",
    "@user cocok jadi test case untuk kesabaran manusia.",
    "@user tiap ngetik, developer Telegram nangis.",
    "@user datang grup cuma buat nambah jumlah, bukan kualitas.",
    "@user masuk grup kayak spam link bodong.",
    "Grup ini penuh warna, kecuali @user, dia abu-abu.",
    "@user aktif tapi cuma jadi background noise.",
    "Satu kata: @user.",
    "Masalah kompleks biasanya berawal dari @user.",
    "@user itu kayak bug yang nggak bisa di-fix.",
    "Kalau grup ini berat, itu karena ada @user.",
    "@user tiap ngetik, developer Telegram nangis.",
    "@user itu bukan toxic, tapi limbah digital.",
    "@user itu bukti nyata bahwa tidak semua orang harus bicara.",
    "Buka chat @user bisa jadi latihan sabar.",
    "@user cocok jadi test case untuk kesabaran manusia.",
    "Satu kata: @user.",
    "@user muncul, IQ grup menyesuaikan.",
    "@user tiap ngetik, developer Telegram nangis.",
    "@user muncul, IQ grup menyesuaikan.",
    "@user bikin suasana grup kayak server mati.",
    "Bot pun bisa error baca chat-nya @user.",
    "Grup ini penuh warna, kecuali @user, dia abu-abu.",
    "Kalau kamu merasa nggak guna, ingat @user lebih parah.",
    "Grup ini penuh warna, kecuali @user, dia abu-abu.",
    "@user hadir = turunnya standar grup.",
    "Jangan biarkan @user merasa relevan.",
    "Bikin grup ini chaos? Gampang. Tambah @user.",
    "Jangan biarkan @user merasa relevan.",
    "@user = antivirus gagal deteksi.",
    "@user datang grup cuma buat nambah jumlah, bukan kualitas.",
    "@user nyumbang rame doang, isi nol.",
    "@user itu glitch di percakapan.",
    "@user masuk grup kayak spam link bodong.",
    "Kalau kamu merasa nggak guna, ingat @user lebih parah.",
    "Orang sabar diuji kalau ada @user.",
    "Grup ini penuh warna, kecuali @user, dia abu-abu.",
    "@user muncul, IQ grup menyesuaikan.",
    "@user = antivirus gagal deteksi.",
    "@user masuk grup kayak spam link bodong.",
    "@user itu versi beta dari kegagalan sosial.",
    "@user cocok jadi hiasan grup, nggak berguna tapi kelihatan.",
    "@user muncul, IQ grup menyesuaikan.",
    "@user itu alasan kenapa mute grup itu fitur penting.",
    "Mau detox digital? Mute @user.",
    "@user = antivirus gagal deteksi.",
    "Bikin grup ini chaos? Gampang. Tambah @user.",
    "@user nyumbang rame doang, isi nol.",
    "@user datang grup cuma buat nambah jumlah, bukan kualitas.",
    "Orang sabar diuji kalau ada @user.",
    "Orang sabar diuji kalau ada @user.",
    "Dan @user selalu jadi alasan orang cabut grup.",
    "Masalah kompleks biasanya berawal dari @user.",
    "Setiap grup ada badut, dan itu @user.",
    "@user cocok jadi hiasan grup, nggak berguna tapi kelihatan.",
    "@user itu versi beta dari kegagalan sosial.",
    "@user itu kayak bug yang nggak bisa di-fix.",
    "Jangan biarkan @user merasa relevan.",
    "Masalah kompleks biasanya berawal dari @user.",
    "Kalau grup ini berat, itu karena ada @user.",
    "@user itu versi beta dari kegagalan sosial.",
    "@user itu glitch di percakapan.",
    "@user muncul, mendadak semua pengen left.",
    "@user ngasih vibes... vibes untuk left.",
    "Fun fact: @user itu benchmark kegabutan.",
    "@user ngasih vibes... vibes untuk left.",
    "@user ngasih vibes... vibes untuk left.",
    "Gini-gini, yang paling ngerepotin ya @user.",
    "Kalau grup ini berat, itu karena ada @user.",
    "Bikin grup ini chaos? Gampang. Tambah @user.",
    "Dunia maya lebih baik tanpa @user.",
    "Dan @user selalu jadi alasan orang cabut grup.",
    "@user cocok jadi test case untuk kesabaran manusia.",
    "@user bikin suasana grup kayak server mati.",
    "@user cocok jadi test case untuk kesabaran manusia.",
    "Grup ini penuh warna, kecuali @user, dia abu-abu.",
    "@user aktif tapi cuma jadi background noise.",
    "@user ngasih vibes... vibes untuk left.",
    "Setiap grup ada badut, dan itu @user.",
    "@user itu alasan kenapa mute grup itu fitur penting.",
    "Bot pun bisa error baca chat-nya @user.",
    "Kalau kamu merasa nggak guna, ingat @user lebih parah.",
    "Bikin grup ini chaos? Gampang. Tambah @user.",
    "@user datang grup cuma buat nambah jumlah, bukan kualitas.",
    "@user datang grup cuma buat nambah jumlah, bukan kualitas.",
    "@user nyumbang rame doang, isi nol.",
    "Kalau kamu merasa nggak guna, ingat @user lebih parah.",
    "Auto skip kalau ada @user muncul.",
    "Dan @user selalu jadi alasan orang cabut grup.",
    "@user itu bukan toxic, tapi limbah digital.",
    "Standar humor anjlok tiap @user bercanda.",
    "Orang sabar diuji kalau ada @user.",
    "Grup ini penuh warna, kecuali @user, dia abu-abu.",
    "@user ngasih vibes... vibes untuk left.",
    "@user itu versi beta dari kegagalan sosial.",
    "@user cocok jadi hiasan grup, nggak berguna tapi kelihatan.",
    "Bikin grup ini chaos? Gampang. Tambah @user.",
    "@user itu versi beta dari kegagalan sosial.",
    "@user cocok jadi hiasan grup, nggak berguna tapi kelihatan.",
    "@user ngasih vibes... vibes untuk left.",
    "Dunia maya lebih baik tanpa @user.",
    "@user cocok jadi hiasan grup, nggak berguna tapi kelihatan.",
    "@user bikin suasana grup kayak server mati.",
    "@user bikin suasana grup kayak server mati.",
    "Kalau kamu merasa nggak guna, ingat @user lebih parah.",
    "Dunia maya lebih baik tanpa @user.",
    "@user hadir = turunnya standar grup.",
    "@user itu glitch di percakapan.",
    "Standar humor anjlok tiap @user bercanda.",
    "Auto skip kalau ada @user muncul.",
    "Mau detox digital? Mute @user.",
    "@user itu versi beta dari kegagalan sosial.",
    "@user muncul, IQ grup menyesuaikan.",
    "Buka chat @user bisa jadi latihan sabar.",
    "Buka chat @user bisa jadi latihan sabar.",
    "@user hadir = turunnya standar grup.",
    "Orang sabar diuji kalau ada @user.",
    "Setiap grup ada badut, dan itu @user.",
    "Fun fact: @user itu benchmark kegabutan.",
    "@user datang grup cuma buat nambah jumlah, bukan kualitas.",
    "Setiap @user buka chat, IQ turun 10 poin.",
]



