import traceback

import config
from helpers import Emoji, Tools, animate_proses
from logs import logger

BLACKBOX_CHAT_URL = "https://api.maelyn.sbs/api/blackbox/chat"
BLACKBOX_IMAGE_URL = "https://api.maelyn.sbs/api/blackbox/image"
BLACKBOX_IMAGINE_URL = "https://api.maelyn.sbs/api/blackbox/imagine"


async def blackbox_cmd(client, message):
    em = Emoji(client)
    await em.get()
    proses = await animate_proses(message, em.proses)

    if len(message.command) < 2:
        return await proses.edit(
            f"{em.gagal}**Please give a prompt or reply with an image and prompt.**"
        )
    prompt = message.text.split(None, 1)[1]
    try:
        headers = {"mg-apikey": config.API_MAELYN}

        if message.reply_to_message and message.reply_to_message.photo:
            if len(message.command) < 2:
                return await proses.edit(
                    f"{em.gagal}**Please provide a prompt to analyze the image.**"
                )
            photo_url = await Tools.maelyn_upload(message)
            params = {"url": photo_url, "q": prompt}
            r = await Tools.fetch.get(
                BLACKBOX_IMAGE_URL, headers=headers, params=params
            )
            if r.status_code != 200:
                return await proses.edit(
                    f"<b>Please try again later: {r.status_code}</b>"
                )
            data = r.json()
            return await proses.edit(data.get("result"))

        elif prompt.lower().startswith("generate "):
            if len(message.command) < 3:
                return await proses.edit(
                    f"{em.gagal}**Please reply to a message prompt or give the prompt!\nExample: `{message.text.split()[0]} cute cats`**"
                )
            prompt = prompt[9:].strip()
            params = {"prompt": prompt}
            r = await Tools.fetch.get(
                BLACKBOX_IMAGINE_URL, headers=headers, params=params
            )
            if r.status_code != 200:
                return await proses.edit(
                    f"<b>Please try again later: {r.status_code}</b>"
                )
            data = r.json()
            img_url = data["result"]["url"]
            await message.reply_photo(
                img_url, caption=f"{em.sukses}**Generated by BlackBox**"
            )
            return await proses.delete()

        else:
            params = {"q": prompt}
            r = await Tools.fetch.get(BLACKBOX_CHAT_URL, headers=headers, params=params)
            if r.status_code != 200:
                return await proses.edit(
                    f"<b>Please try again later: {r.status_code}</b>"
                )
            data = r.json()
            return await proses.edit(data.get("result"))

    except Exception as e:
        logger.error(traceback.format_exc())
        return await proses.edit(f"{em.gagal}**Terjadi kesalahan:**\n`{e}`")


async def deepseek_cmd(client, message):
    em = Emoji(client)
    await em.get()
    proses = await animate_proses(message, em.proses)

    prompt = client.get_text(message)
    if not prompt and not message.reply_to_message:
        return await proses.edit(
            f"{em.gagal}**Please give a prompt or reply with an image and prompt.**"
        )
    chat_id = message.chat.id
    while True:
        try:
            headers = {"mg-apikey": config.API_MAELYN}
            params = {
                "q": prompt,
                "roleplay": "Kamu adalah asisten paling canggih yang berbahasa Indonesia gaul, dan jangan gunakan bahasa inggris sebelum saya memulai duluan",
                "uuid": chat_id,
            }
            url = "https://api.maelyn.sbs/api/deepseek/chat"
            r = await Tools.fetch.get(url, headers=headers, params=params)
            if r.status_code == 200:
                result = r.json()["result"].get("content")
                if len(result) > 4096:
                    with open(f"{prompt.split()[1]}.txt", "wb") as file:
                        file.write(result.encode("utf-8"))
                    reply = await message._client.send_document(
                        chat_id, f"{prompt.split()[1]}.txt"
                    )

                    next_message = await message._client.ask(
                        chat_id,
                        f"**<u>Chat with DeepSeek</u>**\n<b>Question:</b>\n<blockquote>{prompt}</blockquote>\n\n**Type `stopped ask` to end the conversation.**",
                        reply_to_message_id=reply.id,
                        timeout=300,
                    )
                else:
                    if len(result) > 496:
                        caption = f"<blockquote expandable>{result}</blockquote>"
                    else:
                        caption = f"<blockquote>{result}</blockquote>"
                    next_message = await message._client.ask(
                        chat_id,
                        f"<b><u>Chat with DeepSeek</u></b>\n<b>Question:\n<blockquote>{prompt}</blockquote>\n\nAnswer:\n</b>{caption}\n\n**Type `stopped ask` to end the conversation.**",
                    )
                if next_message.text.lower() == "stopped ask":
                    await next_message.reply(f"**Conversation ended.**")
                    break
                next_message.text
            else:
                return await proses.edit("<b>Please try again later..</b>")
        except Exception:
            logger.error(traceback.format_exc())
            return await proses.edit("<b>Please try again later..</b>")
